### ISSUE TITLE
Spatial operators: Kernels not correctly implemented

### ISSUE THREAD

**Issue by Tobias-Fischer** [jhavl/robotacademy-code#20]
In the finding edges lecture, we can use:
K = [0.5, 0, -0.5]
im.convolve(K).disp(colormap="signed")

(see Peter's book, p. 448)

Also, the Sobel kernel is available:

Du=Kernel.Sobel()

**Comment by Tjeard-van-Oort** [comment]
I have updated the usage in the finding edges video, 

Just to clarify since kernels are used in the "Finding Edges" and "Spatial Operators" video did you want me to also update the convolve usage in the spatial operators video to match as well? When I wrote that file I kept it close to the matlab implementation but I can change it as well if you would like.

**Comment by Tobias-Fischer** [comment]
I would recommend to follow the book whenever possible.
