### ISSUE TITLE
Colour images has code but shows as not having code

### ISSUE THREAD

**Issue by Tobias-Fischer** [jhavl/robotacademy-code#24]
https://robotacademy.net.au/masterclass/color/?lesson=716

**Comment by Tjeard-van-Oort** [comment]
I have taken a look and the github repo should have code in the folder for this video, there is a discrepency between the name of the folder and the name of the video however as they do not match on the lesson website as well. 

Lesson name: Color Images in MATLAB
Youtube Video name: Color Image in MATLAB

I am not sure if this is related to how the code on the website is drawing in from the github repo and that the missing code is due to the missmatch in the naming between the video and the actual lesson/folder

**Comment by Tjeard-van-Oort** [comment]
@jhavl Would you be able to check if the webpage for this video is accessing the correct code file in the github directory. If there is a different name the folder should be called please let me know and i will fix it!

**Comment by jhavl** [comment]
Fixed, was a name mismatch as guessed
Thanks!
